---
- name: chaos-shift
  hosts: localhost
  tasks:
  - name: Preparation
    block:
    - name: Check bin and opt directories exist for local user
      file:
        path: ~/{{ item }}
        state: directory
      loop:
        - opt
        - bin
  - name: CodeReady Containers
    block:

    # 2.2. Required software packages for Linux
    # https://code-ready.github.io/crc/#required-software-packages_gsg
    - name: Install CodeReady Containers system package dependencies
      apt:
        name:
        - network-manager
        - libvirt-daemon
        - libvirt-daemon-system
        - qemu-kvm
      become: true

    # 2.3. Installing CodeReady Containers
    # https://code-ready.github.io/crc/#installing-codeready-containers_gsg
    - name: Download CodeReady Containers archive
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.14.0/{{ crc_archive }}
        dest: ./{{ crc_archive }}

    - name: Extract CodeReady Containers archive
      unarchive:
        src: ./{{ crc_archive }}
        dest: ~/opt
        creates: ~/opt/{{ crc_dir }}

    - name: Symlink CodeReady Containers binary to user's bin directory
      file:
        src: ~/opt/{{ crc_dir }}/crc
        dest: ~/bin/crc
        state: link

    - name: CodeReady Containers setup
      command: crc setup

    - name: Start OpenShift cluster
      command: crc start --pull-secret-file pull-secret.json

    vars:
       crc_archive: crc-linux-amd64.tar.xz
       crc_dir: crc-linux-1.14.0-amd64
